version: 2
models:
- name: applicants_adhis_p
  description: ''
  columns:
  - name: citizenship
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/8001475159894173018'
  - name: city
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/2373830726567021255'
  - name: employer_phone
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/614715639179995501'
  - name: sex
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/1469944283301999728'
- name: archived_ssn_adhis_p
  description: ''
  columns:
  - name: contact_id
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_high")}}/2223969292766117270'
  - name: national_id
    description: ''
    policy_tags:
    - projects/sambla-data-staging-compliance/locations/europe-north1/taxonomies/7698000960465061299/policyTags/8190767684129261300
- name: bids_adhis_p
  description: ''
  columns:
  - name: amount
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/5489266776001725763'
- name: credit_report_details_adhis_p
  description: ''
  columns:
  - name: VALUE
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_medium")}}/6031413161488808302'
- name: credit_report_group_items_adhis_p
  description: ''
  columns:
  - name: VALUE
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_medium")}}/6031413161488808302'
- name: creditors_adhis_p
  description: ''
  columns:
  - name: name
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_high")}}/3997340774018070165'
- name: insurance_invoice_items_mutual_adhis_p
  description: ''
  columns:
  - name: AMOUNT
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/5489266776001725763'
- name: insurance_invoice_lines_mutual_adhis_p
  description: ''
  columns:
  - name: AMOUNT
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/5489266776001725763'
- name: insurance_payments_mutual_adhis_p
  description: ''
  columns:
  - name: AMOUNT
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/5489266776001725763'
- name: insurance_repayments_mutual_adhis_p
  description: ''
  columns:
  - name: amount
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/5489266776001725763'
  - name: comments
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_medium")}}/6648053288186094991'
- name: insurance_users_mdn_adhis_p
  description: ''
  columns:
  - name: LAST_NAME
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/7792624092851844015'
  - name: FIRST_NAME
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/5710986738747558502'
- name: invoice_items_gjnsidige_adhis_p
  description: ''
  columns:
  - name: AMOUNT
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/5489266776001725763'
- name: people_adhis_p
  description: ''
  columns:
  - name: national_id
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/8452974265843601388'
- name: subscriptions_adhis_p
  description: ''
  columns:
  - name: amount
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_prod_medium")}}/5489266776001725763'
- name: tags_adhis_p
  description: ''
  columns:
  - name: value
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance_measures_medium")}}/6031413161488808302'
