select
CAST(JSON_VALUE(data,'$.occupation_title') as STRING) AS occupation_title,
CAST(JSON_VALUE(data,'$.civil_status') as INT64) AS civil_status,
CAST(JSON_VALUE(data,'$.home_type') as INT64) AS home_type,
CAST(JSON_VALUE(data,'$.national_id') as STRING) AS national_id,
CAST(JSON_VALUE(data,'$.education_level') as STRING) AS education_level,
CAST(JSON_VALUE(data,'$.employer_name') as STRING) AS employer_name,
CAST(JSON_VALUE(data,'$.employer_phone') as STRING) AS employer_phone,
CAST(JSON_VALUE(data,'$.first_name') as STRING) AS first_name,
CAST(JSON_VALUE(data,'$.postal_code') as STRING) AS postal_code,
CAST(JSON_VALUE(data,'$.email') as STRING) AS email,
CAST(JSON_VALUE(data,'$.monthly_income_before_tax') as INT64) AS monthly_income_before_tax,
CAST(JSON_VALUE(data,'$.monthly_income_after_tax') as STRING) AS monthly_income_after_tax,
CAST(JSON_VALUE(data,'$.employment_type') as INT64) AS employment_type,
CAST(JSON_VALUE(data,'$.employment_to') as TIMESTAMP) AS employment_to,
CAST(JSON_VALUE(data,'$.move_in_date') as STRING) AS move_in_date,
CAST(JSON_VALUE(data,'$.created_at') as TIMESTAMP) AS created_at,
CAST(JSON_VALUE(data,'$.city') as STRING) AS city,
CAST(JSON_VALUE(data,'$.updated_at') as TIMESTAMP) AS updated_at,
CAST(JSON_VALUE(data,'$.id') as INT64) AS id,
CAST(JSON_VALUE(data,'$.last_name') as STRING) AS last_name,
CAST(JSON_VALUE(data,'$.applicant_draft_id') as INT64) AS applicant_draft_id,
CAST(JSON_VALUE(data,'$.spouse_monthly_income_after_tax') as STRING) AS spouse_monthly_income_after_tax,
CAST(JSON_VALUE(data,'$.eu_sanction_validated_at') as TIMESTAMP) AS eu_sanction_validated_at,
CAST(JSON_VALUE(data,'$.country') as STRING) AS country,
CAST(JSON_VALUE(data,'$.latest_credit_default') as STRING) AS latest_credit_default,
CAST(JSON_VALUE(data,'$.home_cost') as INT64) AS home_cost,
CAST(JSON_VALUE(data,'$.customer_id') as INT64) AS customer_id,
CAST(JSON_VALUE(data,'$.num_dependants') as INT64) AS num_dependants,
CAST(CASE WHEN JSON_VALUE(data,'$.is_politically_exposed') = '1' THEN true ELSE false END as BOOLEAN) AS is_politically_exposed,
--CAST(JSON_VALUE(data,'$.employment_since') as TIMESTAMP) AS employment_since,
CAST(case when JSON_VALUE(data,'$.employment_since')='0000-00-00 00:00:00' then '1900-01-01 00:00:00' else JSON_VALUE(data,'$.employment_since') end as TIMESTAMP) AS employment_since,
CAST(JSON_VALUE(data,'$.occupation_category') as STRING) AS occupation_category,
CAST(JSON_VALUE(data,'$.street_address') as STRING) AS street_address,
CAST(case when JSON_VALUE(data,'$.birth_date')='0000-00-00 00:00:00' then '1900-01-01 00:00:00' else JSON_VALUE(data,'$.birth_date') end as TIMESTAMP) AS birth_date,
CAST(JSON_VALUE(data,'$.mobile_phone') as STRING) AS mobile_phone,
CAST(JSON_VALUE(data,'$.country') as STRING) AS citizenship,
CAST(JSON_VALUE(data,'$.military_service_status') as STRING) AS military_service_status,
ts,
DATE(TIMESTAMP_SECONDS(ts)) timestamp_ts,
ROW_NUMBER() over(partition by xid,xoffset,ts order by xid desc, source desc) rn,
source,
xid,
xoffset,
from `${project_id}.${dataset_id}.event_data_sgmw_r`
where table='applicants'
QUALIFY rn = 1
