select
CAST(case JSON_VALUE(data,'$.updated_at') when '0000-00-00 00:00:00' then null else JSON_VALUE(data,'$.updated_at') end as TIMESTAMP) AS updated_at,
CAST(JSON_VALUE(data,'$.name') as STRING) AS name,
CAST(JSON_VALUE(data,'$.postal_address') as STRING) AS postal_address,
CAST(JSON_VALUE(data,'$.minimum_loan_amount') as INT64) AS minimum_loan_amount,
CAST(JSON_VALUE(data,'$.invites_batch_key') as STRING) AS invites_batch_key,
CAST(JSON_VALUE(data,'$.only_last_bid_valid') as STRING) AS only_last_bid_valid,
CAST(JSON_VALUE(data,'$.supports_account_scraping') as STRING) AS supports_account_scraping,
CAST(JSON_VALUE(data,'$.requirements_email') as STRING) AS requirements_email,
CAST(JSON_VALUE(data,'$.creditor_signing_url') as STRING) AS creditor_signing_url,
CAST(JSON_VALUE(data,'$.debt_acquittal_exceptions') as STRING) AS debt_acquittal_exceptions,
CAST(JSON_VALUE(data,'$.average_time_to_bid_in_seconds') as INT64) AS average_time_to_bid_in_seconds,
CAST(JSON_VALUE(data,'$.only_cap_new_loans') as STRING) AS only_cap_new_loans,
CAST(JSON_VALUE(data,'$.id') as INT64) AS id,
CAST(JSON_VALUE(data,'$.arrangement_fee') as INT64) AS arrangement_fee,
CAST(JSON_VALUE(data,'$.payout_to_new_account') as STRING) AS payout_to_new_account,
CAST(JSON_VALUE(data,'$.administration_fee') as INT64) AS administration_fee,
CAST(case JSON_VALUE(data,'$.deactivated_at') when '0000-00-00 00:00:00' then null else JSON_VALUE(data,'$.deactivated_at') end as TIMESTAMP) AS deactivated_at,
CAST(JSON_VALUE(data,'$.requires_bank_account_on_accept') as STRING) AS requires_bank_account_on_accept,
CAST(JSON_VALUE(data,'$.support_updates') as STRING) AS support_updates,
CAST(JSON_VALUE(data,'$.creditor_id') as INT64) AS creditor_id,
CAST(JSON_VALUE(data,'$.loan_amount_multiple_of') as INT64) AS loan_amount_multiple_of,
CAST(JSON_VALUE(data,'$.when_to_send_rejects') as STRING) AS when_to_send_rejects,
CAST(JSON_VALUE(data,'$.debt_letter_delivery_method') as INT64) AS debt_letter_delivery_method,
CAST(JSON_VALUE(data,'$.delayed_filter_other_bid_apr_limit') as STRING) AS delayed_filter_other_bid_apr_limit,
CAST(JSON_VALUE(data,'$.maximum_loan_amount') as INT64) AS maximum_loan_amount,
CAST(JSON_VALUE(data,'$.repayment_time_multiple_of_in_months') as INT64) AS repayment_time_multiple_of_in_months,
CAST(JSON_VALUE(data,'$.delay_invites_seconds_self_service') as STRING) AS delay_invites_seconds_self_service,
CAST(JSON_VALUE(data,'$.decline_old_invite_on_update') as STRING) AS decline_old_invite_on_update,
CAST(JSON_VALUE(data,'$.slug') as STRING) AS slug,
CAST(JSON_VALUE(data,'$.stores_credit_report_num_days') as INT64) AS stores_credit_report_num_days,
CAST(JSON_VALUE(data,'$.average_time_to_payout_in_seconds') as INT64) AS average_time_to_payout_in_seconds,
CAST(JSON_VALUE(data,'$.signing_method') as STRING) AS signing_method,
CAST(JSON_VALUE(data,'$.delayed_filter_apr_limit_only_full_amount') as STRING) AS delayed_filter_apr_limit_only_full_amount,
CAST(JSON_VALUE(data,'$.delay_invites_seconds_advisory') as STRING) AS delay_invites_seconds_advisory,
CAST(JSON_VALUE(data,'$.bids_expiry_time_in_seconds') as INT64) AS bids_expiry_time_in_seconds,
CAST(JSON_VALUE(data,'$.minimum_repayment_time') as INT64) AS minimum_repayment_time,
CAST(JSON_VALUE(data,'$.supports_direct_debit') as STRING) AS supports_direct_debit,
CAST(case JSON_VALUE(data,'$.created_at') when '0000-00-00 00:00:00' then null else JSON_VALUE(data,'$.created_at') end as TIMESTAMP) AS created_at,
CAST(JSON_VALUE(data,'$.maximum_repayment_time') as INT64) AS maximum_repayment_time,
CAST(JSON_VALUE(data,'$.current_filter_version_id') as INT64) AS current_filter_version_id,
CAST(JSON_VALUE(data,'$.repayment_type') as STRING) AS repayment_type,
CAST(JSON_VALUE(data,'$.customer_blocked_months') as INT64) AS customer_blocked_months,
CAST(JSON_VALUE(data,'$.delayed_filter_no_other_bids') as STRING) AS delayed_filter_no_other_bids,
CAST(JSON_VALUE(data,'$.invite_expiry_time_in_seconds') as INT64) AS invite_expiry_time_in_seconds,
CAST(JSON_VALUE(data,'$.supports_auto_undo_accept') as STRING) AS supports_auto_undo_accept,
CAST(JSON_VALUE(data,'$.supports_e_invoice') as STRING) AS supports_e_invoice,
ifnull(CAST(JSON_VALUE(data,'$.application_type') as STRING),'private') AS application_type,
ts,
DATE(TIMESTAMP_SECONDS(ts)) timestamp_ts,
ROW_NUMBER() over(partition by xid,xoffset,ts order by xid desc) rn,
source,
xid,
xoffset,
from {{ref('event_data_sgmw_r')}}
where table='creditor_products'
QUALIFY rn = 1