resource "google_iam_deny_policy" "deny_policy_creation" {
  parent      = urlencode("cloudresourcemanager.googleapis.com/projects/${var.project_id}")  # Corrected parent format
  name        = "gdpr-deny-policy-test"
  display_name = "GDPR deny policy"
  rules {
    description = "First rule"
    deny_rule {
      denied_principals = ["principal://goog/subject/carl.ridnert@samblagroup.com", "principal://goog/subject/google.analytics.sweden@merkle.com", "principal://goog/subject/gelaye.holmer@samblagroup.com", "principal://goog/subject/niklas.selander@samblagroup.com", "principal://goog/subject/nicolaus.benadet@samblagroup.com", "principal://goog/subject/gustaf.vonplomgren@samblagroup.com", "principal://goog/subject/alexander.milles@samblagroup.com", "principal://goog/subject/adam.svenson@samblagroup.com", "principal://goog/subject/suresh.swaminathan@samblagroup.com", "principal://goog/subject/yang.yu@samblagroup.com", "principal://goog/subject/andre.olofsson@samblagroup.com", "principal://goog/subject/ravi.yella@samblagroup.com", "principal://goog/subject/angela.torres@samblagroup.com", "principal://goog/subject/ludvig.wittberger@samblagroup.com", "principal://goog/subject/olivegoldbassethound@samblagroup.com", "principal://goog/subject/alexander.bellamy@samblagroup.com", "principal://goog/subject/gabriel.akira@samblagroup.com", "principal://goog/subject/baris.soybilgen@samblagroup.com", "principal://goog/subject/shio.watanabe@samblagroup.com", "principalSet://goog/group/marketing@samblagroup.com", "principal://goog/subject/peyman.safari@samblagroup.com", "principal://goog/subject/ting.pan@samblagroup.com", "principal://goog/subject/johan.rehnstrom@samblagroup.com", "principal://goog/subject/jing.li@samblagroup.com", "principal://goog/subject/duygu.genc@samblagroup.com", "principal://goog/subject/alexander.nilsson@samblagroup.com"]  # Principals to be denied (all except service accounts and group)
      denial_condition {
        title       = "denial condition expression"
        expression = "resource.matchTagId(\"tagKeys/${google_tags_tag_key.tag_key_prod.name}\", \"tagValues/${google_tags_tag_value.tag_value_prod.name}\")"
      }
      denied_permissions = ["bigquery.googleapis.com/datasets.get", "bigquery.googleapis.com/datasets.update", "bigquery.googleapis.com/tables.create", "bigquery.googleapis.com/tables.delete", "bigquery.googleapis.com/tables.get", "bigquery.googleapis.com/tables.update", "bigquery.googleapis.com/jobs.create", "bigquery.googleapis.com/datasets.create", "bigquery.googleapis.com/jobs.get", "bigquery.googleapis.com/jobs.list", "bigquery.googleapis.com/jobs.listAll", "bigquery.googleapis.com/jobs.delete", "bigquery.googleapis.com/jobs.update", "bigquery.googleapis.com/tables.createIndex", "bigquery.googleapis.com/tables.createSnapshot", "bigquery.googleapis.com/tables.createTagBinding", "bigquery.googleapis.com/tables.deleteIndex", "bigquery.googleapis.com/tables.deleteSnapshot", "bigquery.googleapis.com/tables.deleteTagBinding", "bigquery.googleapis.com/tables.export", "bigquery.googleapis.com/tables.getIamPolicy", "bigquery.googleapis.com/tables.updateData", "bigquery.googleapis.com/models.getData","bigquery.googleapis.com/tables.getData"]  # Permissions to be denied
    }
  }
}
