# utils/config.yml
manifest_path: 'data_input/manifest.json'
catalog_path: 'data_input/catalog.json'
sensitive_field_mapping: 'data_input/sensitive_field_mapping.csv'
sensitive_fields_output_json: '../schemas/policy_tags//sensitive_fields_output.json'
lineage_output_file : 'data_output/column_lineage.yml'
project_id : 'data-domain-data-warehouse'
exclusion_file: 'data_input/exclusion_fields_de_team.txt'
column_mapping_file: 'data_input/column_mapping_de_team.json'

