# utils/config.yml
manifest_path: 'data_input/manifest.json'
catalog_path: 'data_input/catalog.json'
sensitive_field_mapping: 'data_input/sensitive_field_mapping.csv'
<<<<<<< HEAD
sensitive_fields_output_json: '../schemas/policy_tags//sensitive_fields_output.json'
lineage_output_file : 'data_output/column_lineage.yml'
project_id : 'data-domain-data-warehouse'
exclusion_file: 'data_input/exclusion_fields_de_team.txt'
column_mapping_file: 'data_input/column_mapping_de_team.json'

=======
sensitive_fields_output_json: '../schemas/policy_tags//output.json'
lineage_output_file : 'data_output/column_lineage.yml'
project_id : 'data-domain-data-warehouse'
<<<<<<< HEAD
>>>>>>> e994580 (refactoring)
=======
exclusion_file: 'data_input/exclusion_fields_de_team.txt'
column_mapping_file: 'data_input/column_mapping_de_team.json'

>>>>>>> c7e07ef (refactoring and excluding boolean fields)
