project_id: "sambla-data-staging-compliance"
deny_principals:
  - "principal://goog/subject/duygu.genc@samblagroup.com"
tag_key_id: "281476893661836"
tag_value_id: "281478644865264"
denied_permissions:
  - "bigquery.googleapis.com/datasets.get"
  - "bigquery.googleapis.com/datasets.update"
  - "bigquery.googleapis.com/tables.create"
  - "bigquery.googleapis.com/tables.delete"
  - "bigquery.googleapis.com/tables.get"
  - "bigquery.googleapis.com/tables.update"
  - "bigquery.googleapis.com/jobs.create"
  - "bigquery.googleapis.com/datasets.create"
  - "bigquery.googleapis.com/jobs.get"
  - "bigquery.googleapis.com/jobs.list"
  - "bigquery.googleapis.com/jobs.listAll"
  - "bigquery.googleapis.com/jobs.delete"
  - "bigquery.googleapis.com/jobs.update"
  - "bigquery.googleapis.com/tables.createIndex"
  - "bigquery.googleapis.com/tables.createSnapshot"
  - "bigquery.googleapis.com/tables.createTagBinding"
  - "bigquery.googleapis.com/tables.deleteIndex"
  - "bigquery.googleapis.com/tables.deleteSnapshot"
  - "bigquery.googleapis.com/tables.deleteTagBinding"
  - "bigquery.googleapis.com/tables.export"
  - "bigquery.googleapis.com/tables.getIamPolicy"
  - "bigquery.googleapis.com/tables.updateData"
  - "bigquery.googleapis.com/models.getData"

