default:
  anonymization_service:
    exposure_project: "data-domain-data-warehouse"
    raw_layer_project: "sambla-data-staging-compliance"
    compliance_project: "sambla-group-compliance-db"
prod:
  anonymization_service:
    exposure_project: "data-domain-data-warehouse"
    raw_layer_project: "sambla-data-staging-compliance"
    compliance_project: "sambla-group-compliance-db"