default:
  anonymization_service:
    exposure_project: "data-domain-data-warehouse"
    gdpr_events_dataset: "gdpr_events" # change default values for testing
    gdpr_vault_table: "gdpr_vault"
    temp_encr_table: "temp_encrypted_data"
    raw_layer_project: "sambla-data-staging-compliance"
    compliance_project: "sambla-group-compliance-db"
    auth_views_dataset: "authorized_views_test"
prod:
  anonymization_service:
    exposure_project: "data-domain-data-warehouse"
    gdpr_events_dataset: "gdpr_events"
    gdpr_vault_table: "gdpr_vault"
    temp_encr_table: "temp_encrypted_data"
    raw_layer_project: "sambla-data-staging-compliance"
    compliance_project: "sambla-group-compliance-db"
    auth_views_dataset: "authorized_views"