version: 2
models:
- name: applicants_adhis_p
  description: ''
  columns:
  - name: citizenship
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_complaince_measures_medium")}}/4237260191502231235'
  - name: city
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/3997900563213251329'
  - name: employer_name
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/7554052221379315184'
  - name: employer_phone
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/5230172317647726685'
  - name: postal_code
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/2065205436820293935'
- name: insurance_customers_mdn_adhis_p
  description: ''
  columns:
  - name: customer_first_name
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/71389309590075218'
  - name: customer_last_name
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/2716384524483642610'
  - name: customer_gender
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_complaince_measures_medium")}}/7329225061060382501'
  - name: customer_address
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/8460396741430475976'
  - name: customer_address2
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/8460396741430475976'
  - name: customer_postal_code
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/2065205436820293935'
  - name: customer_city
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/3997900563213251329'
  - name: customer_country_code
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/3035155737219158586'
  - name: customer_birth_date
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_complaince_measures_medium")}}/1438955634006760731'
  - name: customer_ssn
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/4818396561666923179'
  - name: customer_phone
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/5230172317647726685'
  - name: customer_phone_mobile
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/5230172317647726685'
  - name: customer_email
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/8192857231542342371'
  - name: customer_passport_issuance_country_code
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/3035155737219158586'
- name: insurance_policies_mdn_adhis_p
  description: ''
  columns:
  - name: user_first_name
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/71389309590075218'
  - name: user_last_name
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/2716384524483642610'
- name: insurance_users_mdn_adhis_p
  description: ''
  columns:
  - name: LAST_NAME
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/2716384524483642610'
  - name: FIRST_NAME
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/71389309590075218'
- name: credit_reports_adhis_p
  description: ''
  columns:
  - name: template_code
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/3035155737219158586'
- name: insurance_repayments_mutual_adhis_p
  description: ''
  columns:
  - name: bank_name
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/5095344055803075463'
- name: insurance_transactions_mdn_adhis_p
  description: ''
  columns:
  - name: USER_LAST_NAME
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/2716384524483642610'
  - name: USER_FIRST_NAME
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/71389309590075218'
- name: insurance_partners_mdn_adhis_p
  description: ''
  columns:
  - name: PARTNER_COUNTRY_CODE
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/3035155737219158586'
- name: people_adhis_p
  description: ''
  columns:
  - name: national_id
    description: ''
    policy_tags:
    - '{{var("policy_tag_gdpr_compliance")}}/8766527890701409234'
