with raw_data AS (
select a.* except(timestamp),
a.timestamp as application_created_at
FROM `${project_id}.${dataset_id}.applications_lvs_r` a
)

select 
cast(a.data_id as string) data_id,
timestamp(a.application_created_at) as application_created_at,
safe_cast(a.processed_datetime as timestamp) as application_processed_at,
a.subid as application_subid,
a.subid2 as application_subid2,
a.subid3 as application_subid3,
a.subid4 as application_subid4,
a.subid5 as application_subid5,
a.ip as ip_address,
a.loanpurpose as loan_purpose,
a.repaymenttime as repayment_time,
a.loanamount as loan_amount,
a.cancelled as cancelled,
a.decision as decision,
a.submit_loan as submit_loan,
a.sent as sent,
safe_cast(a.last_activity_datetime as timestamp) as last_activity_datetime,
a.visit_id as visit_id,
a.status as status,
a.hide_application as hide_application,
a.datamd5 as data_md5,
a.processed as processed,
a.brand_id as source_brand_id,
a.offers as offers,

a.visit.subid as visit_subid,
a.visit.subid2 as visit_subid2,
a.visit.subid3 as visit_subid3,
a.visit.subid4 as visit_subid4,
a.visit.subid5 as visit_subid5,
a.visit.timestamp as visit_updated_at,
a.visit.created_at as visit_created_at,
a.visit.google_client_id as visit_google_client_id,
a.visit.hostname as visit_hostname,
a.visit.hostname2 as visit_hostname2,
a.visit.ip_address2 as visit_ip_address2,
a.visit.maxloan as visit_maxloan,
a.visit.campaign_group as visit_campaign_group,
a.visit.campaign_term as visit_campaign_term,
a.visit.ip_address as visit_ip_address,
a.visit.md5 as visit_md5,
a.visit.referral as visit_referral,
a.visit.campaign as visit_campaign,
a.visit.agent as visit_agent,
a.visit.device_type as visit_device_type,
a.visit.brand as visit_brand,

a.brand.id as brand_id,
a.brand.http_auth as brand_http_auth,
a.brand.double_redirect_url as brand_double_redirect_url,
a.brand.status_url as brand_status_url,
a.brand.reject_redirect_url as brand_reject_redirect_url,
a.brand.google_ua as brand_google_ua,
a.brand.is_active as brand_is_active,
a.brand.has_affiliate_sales as brand_has_affiliate_sales,
a.brand.settings as brand_settings,
a.brand.is_cpl as brand_is_cpl,
a.brand.visible as brand_is_visible,
a.brand.brand as brand,
a.brand.is_omatili as brand_is_omatili,
a.brand.house as brand_house,
a.brand.domain as brand_domain,
a.brand.url as brand_url,
a.brand.omatili_url as brand_omatili_url
from 
raw_data a