default:
  external_table_service:
    project : "data-domain-data-warehouse"
    location: "europe-north1"
    sql_template_path: "policy_tags_service/policy_assignment/templates/get_matching_sensitive_fields.sql"
    policy_tags_script_path: "policy_tags_service/policy_assignment/main.py"
    output_file_name: "external_table_info.txt"
    external_data_info : [
        {
            "legacy_stack": 'salus',
            "dataset_id": 'salus_group_integration',
            "schema":'upstream',
            "table_suffix": "_incremental_r"
        },
        {
            "legacy_stack": "rahalaitos",
            "dataset_id": 'helios_staging',
            "schema":'upstream',
            "table_suffix": "_p"

        }
    ]
    gcs_data_info : [
        {
            "dataset_id":'rahalaitos_data',
            "gcs_bucket_name": 'rahalaitos-data-dump',
            "sink_gcs_bucket_name": 'sambla-group-rahalaitos-integration-legacy',
            "schema": 'rahalaitos'
        },
        {
            "dataset_id":'salus_group_integration',
            "gcs_bucket_name": 'salus-integration',
            "sink_gcs_bucket_name": 'sambla-group-salus-integration-legacy',
            "schema":'salus'

        }
    ]