default:
  authorized_view_service:
    raw_layer_project: "sambla-data-staging-compliance"
    exposure_project: "data-domain-data-warehouse"
    compliance_project: "sambla-group-compliance-db"
    base_folder: "authorized_view_service"
    generate_encrypted: "false"
    generate_cdc: "true"
    gdpr_vault_table: "gdpr_vault_rudolf"
    se_table_names:
        - payments_api__PaymentToProduct_sgds_r
        - marketing_contact_service_contact_tokens_sgds_r
        - exp_bidding_service_creditor_products_sgds_r
        - identity_verification_service_identity_verification_log_sgds_r
        - exp_bidding_service_creditors_sgds_r
        - exp_tracking_service_cookies_sgds_r
        - exp_loan_application_service_applicant_drafts_sgds_r
        - payments_api_Invoice_sgds_r
        - payments_api_Payment_sgds_r
        - marketing_contact_service_contacts_sgds_r
        - exp_loan_application_service_applicants_sgds_r
        - exp_tracking_service_query_params_sgds_r
        - uc_service_credit_reports_sgds_r
        - exp_bidding_service_bidding_logs_sgds_r
        - payments_api_Product_sgds_r
        - credit_report_service_credit_reports_sgds_r
        - marketing_contact_service_fully_blocked_contacts_sgds_r
        - exp_loan_application_service_loan_applications_sgds_r
        - exp_loan_application_service_current_loan_drafts_sgds_r
        - payments_api_Price_sgds_r
        - payments_api_PaymentDetail_sgds_r
        - exp_tracking_service_pageviews_sgds_r
        - exp_loan_application_service_loan_application_drafts_sgds_r
        - exp_bidding_service_bids_sgds_r
        - exp_loan_application_service_current_loans_sgds_r
        - exp_bidding_service_bid_accepts_sgds_r
        - exp_bidding_service_bid_additional_requirements_sgds_r
        - exp_loan_application_service_loan_application_versions_sgds_r
        - exp_bidding_service_invites_sgds_r
        - marketing_contact_service_cart_abandonment_contacts_sgds_r
        - marketing_contact_service_contact_blocks_sgds_r
        - payments_api_Customer_sgds_r
        - exp_bidding_service_bid_logs_sgds_r
        - exp_tracking_service_application_cookie_mappings_sgds_r
        - marketing_contact_service_mortgage_cart_abandonment_contacts_sgds_r
        - payments_api_PaymentEvent_sgds_r
        - payments_api_InvoiceFile_sgds_r
        - payments_api_InvoiceItem_sgds_r
        - payments_api_RecurringPayment_sgds_r
        - exp_bidding_service_invite_logs_sgds_r
        - payments_api_RecurringPaymentEvent_sgds_r
        - exp_customer_service_customers_sgds_r
    fi_table_names:
        - asiakastieto_service_credit_defaults_sgds_r
        - marketing_contact_service_contact_tokens_sgds_r
        - exp_bidding_service_creditor_products_sgds_r
        - identity_verification_service_identity_verification_log_sgds_r
        - exp_bidding_service_creditors_sgds_r
        - exp_tracking_service_cookies_sgds_r
        - exp_loan_application_service_applicant_drafts_sgds_r
        - marketing_contact_service_contacts_sgds_r
        - exp_loan_application_service_applicants_sgds_r
        - exp_tracking_service_query_params_sgds_r
        - asiakastieto_service_credit_default_rows_sgds_r
        - exp_bidding_service_bidding_logs_sgds_r
        - credit_report_service_credit_reports_sgds_r
        - marketing_contact_service_fully_blocked_contacts_sgds_r
        - exp_loan_application_service_loan_applications_sgds_r
        - exp_loan_application_service_current_loan_drafts_sgds_r
        - exp_tracking_service_pageviews_sgds_r
        - bisnode_service_credit_reports_sgds_r
        - exp_loan_application_service_loan_application_drafts_sgds_r
        - exp_bidding_service_bids_sgds_r
        - exp_loan_application_service_current_loans_sgds_r
        - exp_bidding_service_bid_accepts_sgds_r
        - exp_bidding_service_bid_additional_requirements_sgds_r
        - exp_loan_application_service_loan_application_versions_sgds_r
        - exp_bidding_service_invites_sgds_r
        - marketing_contact_service_cart_abandonment_contacts_sgds_r
        - marketing_contact_service_contact_blocks_sgds_r
        - exp_bidding_service_bid_logs_sgds_r
        - exp_tracking_service_application_cookie_mappings_sgds_r
        - exp_bidding_service_invite_logs_sgds_r
        - exp_customer_service_customers_sgds_r
    no_table_names:
        - marketing_contact_service_contact_tokens_sgds_r
        - exp_bidding_service_creditor_products_sgds_r
        - identity_verification_service_identity_verification_log_sgds_r
        - exp_bidding_service_creditors_sgds_r
        - exp_tracking_service_cookies_sgds_r
        - exp_loan_application_service_applicant_drafts_sgds_r
        - eiendomsverdi_service_real_estates_sgds_r
        - marketing_contact_service_contacts_sgds_r
        - exp_loan_application_service_applicants_sgds_r
        - eiendomsverdi_service_reports_sgds_r
        - exp_tracking_service_query_params_sgds_r
        - exp_bidding_service_bidding_logs_sgds_r
        - credit_report_service_credit_reports_sgds_r
        - marketing_contact_service_fully_blocked_contacts_sgds_r
        - exp_loan_application_service_loan_applications_sgds_r
        - exp_loan_application_service_current_loan_drafts_sgds_r
        - eiendomsverdi_service_mortgages_sgds_r
        - exp_tracking_service_pageviews_sgds_r
        - exp_loan_application_service_loan_application_drafts_sgds_r
        - gjeldsregisteret_service_loans_sgds_r
        - exp_bidding_service_bids_sgds_r
        - exp_loan_application_service_current_loans_sgds_r
        - exp_bidding_service_bid_accepts_sgds_r
        - gjeldsregisteret_service_consents_sgds_r
        - exp_bidding_service_bid_additional_requirements_sgds_r
        - exp_loan_application_service_loan_application_versions_sgds_r
        - exp_bidding_service_invites_sgds_r
        - marketing_contact_service_cart_abandonment_contacts_sgds_r
        - marketing_contact_service_contact_blocks_sgds_r
        - exp_bidding_service_bid_logs_sgds_r
        - exp_tracking_service_application_cookie_mappings_sgds_r
        - experian_service_credit_reports_sgds_r
        - exp_bidding_service_invite_logs_sgds_r
        - exp_customer_service_customers_sgds_r
prod:
  authorized_view_service:
    raw_layer_project: "sambla-data-staging-compliance"
    exposure_project: "data-domain-data-warehouse"
    compliance_project: "sambla-group-compliance-db"
    base_folder: "authorized_view_service"
    generate_encrypted: "true"
    generate_cdc: "true"
    gdpr_vault_table: "gdpr_vault_rudolf"
    se_table_names:
        - payments_api__PaymentToProduct_sgds_r
        - marketing_contact_service_contact_tokens_sgds_r
        - exp_bidding_service_creditor_products_sgds_r
        - identity_verification_service_identity_verification_log_sgds_r
        - exp_bidding_service_creditors_sgds_r
        - exp_tracking_service_cookies_sgds_r
        - exp_loan_application_service_applicant_drafts_sgds_r
        - payments_api_Invoice_sgds_r
        - payments_api_Payment_sgds_r
        - marketing_contact_service_contacts_sgds_r
        - exp_loan_application_service_applicants_sgds_r
        - exp_tracking_service_query_params_sgds_r
        - uc_service_credit_reports_sgds_r
        - exp_bidding_service_bidding_logs_sgds_r
        - payments_api_Product_sgds_r
        - credit_report_service_credit_reports_sgds_r
        - marketing_contact_service_fully_blocked_contacts_sgds_r
        - exp_loan_application_service_loan_applications_sgds_r
        - exp_loan_application_service_current_loan_drafts_sgds_r
        - payments_api_Price_sgds_r
        - payments_api_PaymentDetail_sgds_r
        - exp_tracking_service_pageviews_sgds_r
        - exp_loan_application_service_loan_application_drafts_sgds_r
        - exp_bidding_service_bids_sgds_r
        - exp_loan_application_service_current_loans_sgds_r
        - exp_bidding_service_bid_accepts_sgds_r
        - exp_bidding_service_bid_additional_requirements_sgds_r
        - exp_loan_application_service_loan_application_versions_sgds_r
        - exp_bidding_service_invites_sgds_r
        - marketing_contact_service_cart_abandonment_contacts_sgds_r
        - marketing_contact_service_contact_blocks_sgds_r
        - payments_api_Customer_sgds_r
        - exp_bidding_service_bid_logs_sgds_r
        - exp_tracking_service_application_cookie_mappings_sgds_r
        - marketing_contact_service_mortgage_cart_abandonment_contacts_sgds_r
        - payments_api_PaymentEvent_sgds_r
        - payments_api_InvoiceFile_sgds_r
        - payments_api_InvoiceItem_sgds_r
        - payments_api_RecurringPayment_sgds_r
        - exp_bidding_service_invite_logs_sgds_r
        - payments_api_RecurringPaymentEvent_sgds_r
        - exp_customer_service_customers_sgds_r
    fi_table_names:
        - asiakastieto_service_credit_defaults_sgds_r
        - marketing_contact_service_contact_tokens_sgds_r
        - exp_bidding_service_creditor_products_sgds_r
        - identity_verification_service_identity_verification_log_sgds_r
        - exp_bidding_service_creditors_sgds_r
        - exp_tracking_service_cookies_sgds_r
        - exp_loan_application_service_applicant_drafts_sgds_r
        - marketing_contact_service_contacts_sgds_r
        - exp_loan_application_service_applicants_sgds_r
        - exp_tracking_service_query_params_sgds_r
        - asiakastieto_service_credit_default_rows_sgds_r
        - exp_bidding_service_bidding_logs_sgds_r
        - credit_report_service_credit_reports_sgds_r
        - marketing_contact_service_fully_blocked_contacts_sgds_r
        - exp_loan_application_service_loan_applications_sgds_r
        - exp_loan_application_service_current_loan_drafts_sgds_r
        - exp_tracking_service_pageviews_sgds_r
        - bisnode_service_credit_reports_sgds_r
        - exp_loan_application_service_loan_application_drafts_sgds_r
        - exp_bidding_service_bids_sgds_r
        - exp_loan_application_service_current_loans_sgds_r
        - exp_bidding_service_bid_accepts_sgds_r
        - exp_bidding_service_bid_additional_requirements_sgds_r
        - exp_loan_application_service_loan_application_versions_sgds_r
        - exp_bidding_service_invites_sgds_r
        - marketing_contact_service_cart_abandonment_contacts_sgds_r
        - marketing_contact_service_contact_blocks_sgds_r
        - exp_bidding_service_bid_logs_sgds_r
        - exp_tracking_service_application_cookie_mappings_sgds_r
        - exp_bidding_service_invite_logs_sgds_r
        - exp_customer_service_customers_sgds_r
    no_table_names:
        - marketing_contact_service_contact_tokens_sgds_r
        - exp_bidding_service_creditor_products_sgds_r
        - identity_verification_service_identity_verification_log_sgds_r
        - exp_bidding_service_creditors_sgds_r
        - exp_tracking_service_cookies_sgds_r
        - exp_loan_application_service_applicant_drafts_sgds_r
        - eiendomsverdi_service_real_estates_sgds_r
        - marketing_contact_service_contacts_sgds_r
        - exp_loan_application_service_applicants_sgds_r
        - eiendomsverdi_service_reports_sgds_r
        - exp_tracking_service_query_params_sgds_r
        - exp_bidding_service_bidding_logs_sgds_r
        - credit_report_service_credit_reports_sgds_r
        - marketing_contact_service_fully_blocked_contacts_sgds_r
        - exp_loan_application_service_loan_applications_sgds_r
        - exp_loan_application_service_current_loan_drafts_sgds_r
        - eiendomsverdi_service_mortgages_sgds_r
        - exp_tracking_service_pageviews_sgds_r
        - exp_loan_application_service_loan_application_drafts_sgds_r
        - gjeldsregisteret_service_loans_sgds_r
        - exp_bidding_service_bids_sgds_r
        - exp_loan_application_service_current_loans_sgds_r
        - exp_bidding_service_bid_accepts_sgds_r
        - gjeldsregisteret_service_consents_sgds_r
        - exp_bidding_service_bid_additional_requirements_sgds_r
        - exp_loan_application_service_loan_application_versions_sgds_r
        - exp_bidding_service_invites_sgds_r
        - marketing_contact_service_cart_abandonment_contacts_sgds_r
        - marketing_contact_service_contact_blocks_sgds_r
        - exp_bidding_service_bid_logs_sgds_r
        - exp_tracking_service_application_cookie_mappings_sgds_r
        - experian_service_credit_reports_sgds_r
        - exp_bidding_service_invite_logs_sgds_r
        - exp_customer_service_customers_sgds_r