default:
  authorized_view_service:
    raw_layer_project: "sambla-data-staging-compliance"
    exposure_project: "data-domain-exposure-project"
    compliance_project: "sambla-group-compliance-db"
    base_path: "./prod/authorized_view_service"
    service_account_key: "/Users/duygugenc/Documents/de-ingestion-staging-layer-filtering/sambla-data-staging-compliance-gcs-handler.json"

prod:
  authorized_view_service:
    raw_layer_project: "sambla-data-staging-compliance"
    exposure_project: "data-domain-exposure-project"
    compliance_project: "sambla-group-compliance-db"
    base_path: "./prod/authorized_view_service"
    service_account_key: "/Users/duygugenc/Documents/de-ingestion-staging-layer-filtering/sambla-data-staging-compliance-gcs-handler.json"
