default:
  authorized_view_service:
    raw_layer_project: "sambla-data-staging-compliance"
    exposure_project: "data-domain-data-warehouse"
    compliance_project: "sambla-group-compliance-db"
    base_folder: "authorized_view_service"
    generate_encrypted: "false"
    gdpr_vault_table: "gdpr_vault_rudolf"

prod:
  authorized_view_service:
    raw_layer_project: "sambla-data-staging-compliance"
    exposure_project: "data-domain-data-warehouse"
    compliance_project: "sambla-group-compliance-db"
    base_folder: "authorized_view_service"
    generate_encrypted: "false"
    gdpr_vault_table: "gdpr_vault_rudolf"
