default:
  policy_tags_service:
    raw_layer_project: "sambla-data-staging-compliance"
    project_location: "europe-north1"
    base_path: "prod/policy_tags_service"
    schema_file_path: "prod/schemas"
    service_account_key: "/Users/duygugenc/Documents/de-ingestion-staging-layer-filtering/sambla-data-staging-compliance-gcs-handler.json"
    terraform_sa_key: "/Users/duygugenc/Documents/de-ingestion-staging-layer/prod/service_accounts_keyfiles/sambla-data-staging-compliance-8044831a0873.json"
prod:
  policy_tags_service:
    raw_layer_project: "sambla-data-staging-compliance"
    project_location: "europe-north1"
    base_path: ".prod/policy_tags_service"
    schema_file_path: "prod/schemas"
    service_account_key: "/Users/duygugenc/Documents/de-ingestion-staging-layer-filtering/sambla-data-staging-compliance-gcs-handler.json"
