default:
  policy_tags_service:
    raw_layer_project: "sambla-data-staging-compliance"
    project_location: "europe-north1"
    terraform_sa_secret_name: "terraform-adm-secret-sa"
prod:
  policy_tags_service:
    raw_layer_project: "sambla-data-staging-compliance"
    project_location: "europe-north1"
    terraform_sa_secret_name: "terraform-adm-secret-sa"

