default:
  policy_tags_service:
    raw_layer_project: "sambla-data-staging-compliance"
    project_location: "europe-north1"
prod:
  policy_tags_service:
    raw_layer_project: "sambla-data-staging-compliance"
    project_location: "europe-north1"
